# Generated by Django 2.2.11 on 2020-03-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='registeredfaces',
            name='image_encoding',
        ),
    ]
