# Generated by Django 2.2.11 on 2020-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registeredfaces_image_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredfaces',
            name='identification_number',
            field=models.CharField(max_length=15),
        ),
    ]
